"""create initial schema

Revision ID: c980ff6470d2
Revises:
Create Date: 2026-10-04 23:57:07.325566
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c980ff6470d2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
    )
    op.create_index(op.f("ix_ingredients_category"), "ingredients", ["category"], unique=False)
    op.create_index(op.f("ix_ingredients_name"), "ingredients", ["name"], unique=True)
    op.create_table(
        "recipes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cuisine", sa.String(length=64), nullable=False),
        sa.Column("meal_type", sa.String(length=32), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("protein_g", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("carbs_g", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("fat_g", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("preparation_minutes", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("calories > 0", name=op.f("ck_recipes_positive_calories")),
        sa.CheckConstraint("carbs_g >= 0", name=op.f("ck_recipes_nonnegative_carbs")),
        sa.CheckConstraint(
            "estimated_cost >= 0", name=op.f("ck_recipes_nonnegative_estimated_cost")
        ),
        sa.CheckConstraint("fat_g >= 0", name=op.f("ck_recipes_nonnegative_fat")),
        sa.CheckConstraint(
            "preparation_minutes > 0", name=op.f("ck_recipes_positive_preparation_minutes")
        ),
        sa.CheckConstraint("protein_g >= 0", name=op.f("ck_recipes_nonnegative_protein")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
    )
    op.create_index(op.f("ix_recipes_cuisine"), "recipes", ["cuisine"], unique=False)
    op.create_index(op.f("ix_recipes_meal_type"), "recipes", ["meal_type"], unique=False)
    op.create_index(op.f("ix_recipes_name"), "recipes", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "cuisine_preferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("cuisine", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_cuisine_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cuisine_preferences")),
        sa.UniqueConstraint("user_id", "cuisine", name=op.f("uq_cuisine_preferences_user_id")),
    )
    op.create_index(
        op.f("ix_cuisine_preferences_user_id"), "cuisine_preferences", ["user_id"], unique=False
    )
    op.create_table(
        "ingredient_cuisine_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.Column("cuisine", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_ingredient_cuisine_tags_ingredient_id_ingredients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredient_cuisine_tags")),
        sa.UniqueConstraint(
            "ingredient_id", "cuisine", name=op.f("uq_ingredient_cuisine_tags_ingredient_id")
        ),
    )
    op.create_index(
        op.f("ix_ingredient_cuisine_tags_cuisine"),
        "ingredient_cuisine_tags",
        ["cuisine"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingredient_cuisine_tags_ingredient_id"),
        "ingredient_cuisine_tags",
        ["ingredient_id"],
        unique=False,
    )
    op.create_table(
        "meal_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("meal_type", sa.String(length=32), nullable=False),
        sa.Column("food_name", sa.String(length=160), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("calories > 0", name=op.f("ck_meal_logs_positive_calories")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_meal_logs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meal_logs")),
    )
    op.create_index(op.f("ix_meal_logs_meal_type"), "meal_logs", ["meal_type"], unique=False)
    op.create_index(op.f("ix_meal_logs_occurred_at"), "meal_logs", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_meal_logs_user_id"), "meal_logs", ["user_id"], unique=False)
    op.create_table(
        "meal_schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("meal_type", sa.String(length=32), nullable=False),
        sa.Column("preferred_time", sa.Time(), nullable=False),
        sa.Column("reminder_minutes_before", sa.Integer(), server_default="15", nullable=False),
        sa.Column("reminder_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reminder_minutes_before BETWEEN 0 AND 180",
            name=op.f("ck_meal_schedules_reminder_lead_time_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_meal_schedules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meal_schedules")),
        sa.UniqueConstraint("user_id", "meal_type", name=op.f("uq_meal_schedules_user_id")),
    )
    op.create_index(op.f("ix_meal_schedules_user_id"), "meal_schedules", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("meal_type", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "generated",
                "read",
                "failed",
                name="notificationstatus",
                native_enum=False,
                create_constraint=False,
                length=20,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'generated', 'read', 'failed')",
            name=op.f("ck_notifications_notificationstatus"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_scheduled_for"), "notifications", ["scheduled_for"], unique=False
    )
    op.create_index(op.f("ix_notifications_status"), "notifications", ["status"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "pantry_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "available",
                "low",
                "unavailable",
                name="pantrystatus",
                native_enum=False,
                create_constraint=False,
                length=20,
            ),
            server_default="available",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('available', 'low', 'unavailable')",
            name=op.f("ck_pantry_items_pantrystatus"),
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_pantry_items_ingredient_id_ingredients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_pantry_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pantry_items")),
        sa.UniqueConstraint("user_id", "ingredient_id", name=op.f("uq_pantry_items_user_id")),
    )
    op.create_index(
        op.f("ix_pantry_items_ingredient_id"), "pantry_items", ["ingredient_id"], unique=False
    )
    op.create_index(op.f("ix_pantry_items_user_id"), "pantry_items", ["user_id"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "activity_level",
            sa.Enum(
                "sedentary",
                "light",
                "moderate",
                "active",
                "very_active",
                name="activitylevel",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "goal_type",
            sa.Enum(
                "lose_weight",
                "maintain_weight",
                "gain_weight",
                name="goaltype",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("goal_weight_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("daily_calorie_target", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activity_level IN ('sedentary', 'light', 'moderate', 'active', 'very_active')",
            name=op.f("ck_profiles_activitylevel"),
        ),
        sa.CheckConstraint(
            "goal_type IN ('lose_weight', 'maintain_weight', 'gain_weight')",
            name=op.f("ck_profiles_goaltype"),
        ),
        sa.CheckConstraint("age BETWEEN 13 AND 120", name=op.f("ck_profiles_age_range")),
        sa.CheckConstraint(
            "daily_calorie_target BETWEEN 800 AND 10000",
            name=op.f("ck_profiles_calorie_target_range"),
        ),
        sa.CheckConstraint(
            "goal_weight_kg IS NULL OR goal_weight_kg BETWEEN 25 AND 500",
            name=op.f("ck_profiles_goal_weight_range"),
        ),
        sa.CheckConstraint("height_cm BETWEEN 80 AND 250", name=op.f("ck_profiles_height_range")),
        sa.CheckConstraint("weight_kg BETWEEN 25 AND 500", name=op.f("ck_profiles_weight_range")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
    )
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_table(
        "recipe_ingredients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_text", sa.String(length=80), nullable=True),
        sa.Column("is_optional", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_recipe_ingredients_ingredient_id_ingredients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_ingredients_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_ingredients")),
        sa.UniqueConstraint(
            "recipe_id", "ingredient_id", name=op.f("uq_recipe_ingredients_recipe_id")
        ),
    )
    op.create_index(
        op.f("ix_recipe_ingredients_ingredient_id"),
        "recipe_ingredients",
        ["ingredient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipe_ingredients_recipe_id"), "recipe_ingredients", ["recipe_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipe_ingredients_recipe_id"), table_name="recipe_ingredients")
    op.drop_index(op.f("ix_recipe_ingredients_ingredient_id"), table_name="recipe_ingredients")
    op.drop_table("recipe_ingredients")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_pantry_items_user_id"), table_name="pantry_items")
    op.drop_index(op.f("ix_pantry_items_ingredient_id"), table_name="pantry_items")
    op.drop_table("pantry_items")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_scheduled_for"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_meal_schedules_user_id"), table_name="meal_schedules")
    op.drop_table("meal_schedules")
    op.drop_index(op.f("ix_meal_logs_user_id"), table_name="meal_logs")
    op.drop_index(op.f("ix_meal_logs_occurred_at"), table_name="meal_logs")
    op.drop_index(op.f("ix_meal_logs_meal_type"), table_name="meal_logs")
    op.drop_table("meal_logs")
    op.drop_index(
        op.f("ix_ingredient_cuisine_tags_ingredient_id"), table_name="ingredient_cuisine_tags"
    )
    op.drop_index(op.f("ix_ingredient_cuisine_tags_cuisine"), table_name="ingredient_cuisine_tags")
    op.drop_table("ingredient_cuisine_tags")
    op.drop_index(op.f("ix_cuisine_preferences_user_id"), table_name="cuisine_preferences")
    op.drop_table("cuisine_preferences")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_recipes_name"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_meal_type"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_cuisine"), table_name="recipes")
    op.drop_table("recipes")
    op.drop_index(op.f("ix_ingredients_name"), table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_category"), table_name="ingredients")
    op.drop_table("ingredients")
    # ### end Alembic commands ###
