from typing import TypedDict


class IngredientSeed(TypedDict):
    name: str
    category: str
    cuisines: list[str]


class RecipeSeed(TypedDict):
    name: str
    description: str
    cuisine: str
    meal_type: str
    calories: int
    protein_g: float
    carbs_g: float
    fat_g: float
    preparation_minutes: int
    estimated_cost: float
    ingredients: list[str]


INGREDIENTS: list[IngredientSeed] = [
    {
        "name": "rice",
        "category": "grains",
        "cuisines": ["Indian", "Chinese", "Korean", "Japanese", "Thai"],
    },
    {
        "name": "lentils",
        "category": "legumes",
        "cuisines": ["Indian", "Mediterranean", "Middle Eastern"],
    },
    {
        "name": "eggs",
        "category": "protein",
        "cuisines": ["American", "Chinese", "Korean", "Japanese"],
    },
    {
        "name": "yogurt",
        "category": "dairy",
        "cuisines": ["Indian", "Mediterranean", "Middle Eastern"],
    },
    {"name": "paneer", "category": "dairy", "cuisines": ["Indian"]},
    {
        "name": "onion",
        "category": "produce",
        "cuisines": ["Indian", "Mexican", "Italian", "American", "Mediterranean", "Middle Eastern"],
    },
    {
        "name": "tomato",
        "category": "produce",
        "cuisines": ["Indian", "Mexican", "Italian", "Mediterranean", "Middle Eastern"],
    },
    {
        "name": "chickpeas",
        "category": "legumes",
        "cuisines": ["Indian", "Mediterranean", "Middle Eastern"],
    },
    {"name": "tortillas", "category": "grains", "cuisines": ["Mexican"]},
    {"name": "black beans", "category": "legumes", "cuisines": ["Mexican"]},
    {"name": "salsa", "category": "condiments", "cuisines": ["Mexican"]},
    {"name": "avocado", "category": "produce", "cuisines": ["Mexican", "American"]},
    {"name": "cheddar cheese", "category": "dairy", "cuisines": ["Mexican", "American"]},
    {
        "name": "chicken breast",
        "category": "protein",
        "cuisines": [
            "Indian",
            "Mexican",
            "Chinese",
            "Italian",
            "American",
            "Mediterranean",
            "Korean",
            "Thai",
            "Middle Eastern",
        ],
    },
    {"name": "pasta", "category": "grains", "cuisines": ["Italian", "American"]},
    {"name": "parmesan", "category": "dairy", "cuisines": ["Italian"]},
    {
        "name": "olive oil",
        "category": "oils",
        "cuisines": ["Italian", "Mediterranean", "Middle Eastern"],
    },
    {"name": "spinach", "category": "produce", "cuisines": ["Indian", "Italian", "Mediterranean"]},
    {"name": "quinoa", "category": "grains", "cuisines": ["American", "Mediterranean"]},
    {"name": "cucumber", "category": "produce", "cuisines": ["Mediterranean", "Middle Eastern"]},
    {"name": "feta", "category": "dairy", "cuisines": ["Mediterranean", "Middle Eastern"]},
    {"name": "salmon", "category": "protein", "cuisines": ["American", "Japanese"]},
    {"name": "broccoli", "category": "produce", "cuisines": ["American", "Chinese"]},
    {"name": "soy sauce", "category": "condiments", "cuisines": ["Chinese", "Korean", "Japanese"]},
    {"name": "tofu", "category": "protein", "cuisines": ["Chinese", "Korean", "Japanese", "Thai"]},
    {"name": "sesame oil", "category": "oils", "cuisines": ["Chinese", "Korean", "Japanese"]},
    {"name": "kimchi", "category": "produce", "cuisines": ["Korean"]},
    {"name": "gochujang", "category": "condiments", "cuisines": ["Korean"]},
    {"name": "seaweed", "category": "pantry", "cuisines": ["Japanese", "Korean"]},
    {"name": "miso paste", "category": "condiments", "cuisines": ["Japanese"]},
    {"name": "noodles", "category": "grains", "cuisines": ["Chinese", "Japanese", "Thai"]},
    {"name": "coconut milk", "category": "pantry", "cuisines": ["Indian", "Thai"]},
    {
        "name": "bell pepper",
        "category": "produce",
        "cuisines": ["Mexican", "Chinese", "Italian", "Thai"],
    },
    {"name": "peanut butter", "category": "pantry", "cuisines": ["Thai", "American"]},
    {"name": "hummus", "category": "condiments", "cuisines": ["Mediterranean", "Middle Eastern"]},
    {"name": "pita", "category": "grains", "cuisines": ["Mediterranean", "Middle Eastern"]},
    {"name": "ground turkey", "category": "protein", "cuisines": ["American"]},
    {"name": "oats", "category": "grains", "cuisines": ["American"]},
    {"name": "banana", "category": "produce", "cuisines": ["American"]},
    {
        "name": "garlic",
        "category": "produce",
        "cuisines": [
            "Indian",
            "Chinese",
            "Italian",
            "Mediterranean",
            "Korean",
            "Thai",
            "Middle Eastern",
        ],
    },
]


RECIPES: list[RecipeSeed] = [
    {
        "name": "Chickpea Rice Bowl",
        "description": "Spiced chickpeas, rice, tomato, and cooling yogurt.",
        "cuisine": "Indian",
        "meal_type": "lunch",
        "calories": 560,
        "protein_g": 22,
        "carbs_g": 88,
        "fat_g": 13,
        "preparation_minutes": 20,
        "estimated_cost": 4.5,
        "ingredients": ["rice", "chickpeas", "tomato", "onion", "yogurt"],
    },
    {
        "name": "Paneer Spinach Skillet",
        "description": "Fast paneer and spinach skillet with tomato and rice.",
        "cuisine": "Indian",
        "meal_type": "dinner",
        "calories": 610,
        "protein_g": 31,
        "carbs_g": 57,
        "fat_g": 29,
        "preparation_minutes": 25,
        "estimated_cost": 6.25,
        "ingredients": ["paneer", "spinach", "tomato", "onion", "rice"],
    },
    {
        "name": "Black Bean Breakfast Tacos",
        "description": "Egg, black bean, salsa, and avocado tacos.",
        "cuisine": "Mexican",
        "meal_type": "breakfast",
        "calories": 470,
        "protein_g": 24,
        "carbs_g": 52,
        "fat_g": 20,
        "preparation_minutes": 15,
        "estimated_cost": 4.75,
        "ingredients": ["tortillas", "black beans", "eggs", "salsa", "avocado"],
    },
    {
        "name": "Chicken Burrito Bowl",
        "description": "Chicken, rice, black beans, salsa, and avocado.",
        "cuisine": "Mexican",
        "meal_type": "lunch",
        "calories": 650,
        "protein_g": 43,
        "carbs_g": 76,
        "fat_g": 20,
        "preparation_minutes": 25,
        "estimated_cost": 7.0,
        "ingredients": ["chicken breast", "rice", "black beans", "salsa", "avocado"],
    },
    {
        "name": "Tomato Spinach Pasta",
        "description": "Pasta tossed with tomato, spinach, garlic, and parmesan.",
        "cuisine": "Italian",
        "meal_type": "dinner",
        "calories": 590,
        "protein_g": 23,
        "carbs_g": 86,
        "fat_g": 18,
        "preparation_minutes": 22,
        "estimated_cost": 5.5,
        "ingredients": ["pasta", "tomato", "spinach", "garlic", "parmesan", "olive oil"],
    },
    {
        "name": "Mediterranean Quinoa Bowl",
        "description": "Quinoa, chickpeas, cucumber, tomato, feta, and yogurt.",
        "cuisine": "Mediterranean",
        "meal_type": "lunch",
        "calories": 520,
        "protein_g": 24,
        "carbs_g": 68,
        "fat_g": 18,
        "preparation_minutes": 18,
        "estimated_cost": 5.75,
        "ingredients": ["quinoa", "chickpeas", "cucumber", "tomato", "feta", "yogurt"],
    },
    {
        "name": "Salmon Broccoli Rice",
        "description": "Roasted salmon and broccoli over rice.",
        "cuisine": "American",
        "meal_type": "dinner",
        "calories": 620,
        "protein_g": 42,
        "carbs_g": 61,
        "fat_g": 23,
        "preparation_minutes": 25,
        "estimated_cost": 9.5,
        "ingredients": ["salmon", "broccoli", "rice", "olive oil"],
    },
    {
        "name": "Banana Yogurt Oats",
        "description": "Oats with yogurt, banana, and peanut butter.",
        "cuisine": "American",
        "meal_type": "breakfast",
        "calories": 430,
        "protein_g": 20,
        "carbs_g": 62,
        "fat_g": 13,
        "preparation_minutes": 8,
        "estimated_cost": 2.75,
        "ingredients": ["oats", "yogurt", "banana", "peanut butter"],
    },
    {
        "name": "Tofu Vegetable Stir Fry",
        "description": "Tofu, broccoli, and pepper stir-fried with soy and sesame.",
        "cuisine": "Chinese",
        "meal_type": "dinner",
        "calories": 540,
        "protein_g": 29,
        "carbs_g": 65,
        "fat_g": 20,
        "preparation_minutes": 20,
        "estimated_cost": 5.25,
        "ingredients": ["tofu", "broccoli", "bell pepper", "soy sauce", "sesame oil", "rice"],
    },
    {
        "name": "Kimchi Egg Rice Bowl",
        "description": "Rice bowl with egg, kimchi, seaweed, and sesame.",
        "cuisine": "Korean",
        "meal_type": "lunch",
        "calories": 510,
        "protein_g": 21,
        "carbs_g": 72,
        "fat_g": 16,
        "preparation_minutes": 15,
        "estimated_cost": 4.25,
        "ingredients": ["rice", "eggs", "kimchi", "seaweed", "sesame oil"],
    },
    {
        "name": "Miso Salmon Rice Bowl",
        "description": "Miso-glazed salmon with rice and seaweed.",
        "cuisine": "Japanese",
        "meal_type": "dinner",
        "calories": 600,
        "protein_g": 40,
        "carbs_g": 65,
        "fat_g": 21,
        "preparation_minutes": 25,
        "estimated_cost": 9.0,
        "ingredients": ["salmon", "miso paste", "rice", "seaweed", "soy sauce"],
    },
    {
        "name": "Thai Peanut Tofu Noodles",
        "description": "Quick tofu noodles with peanut, coconut, and pepper sauce.",
        "cuisine": "Thai",
        "meal_type": "dinner",
        "calories": 640,
        "protein_g": 28,
        "carbs_g": 78,
        "fat_g": 25,
        "preparation_minutes": 24,
        "estimated_cost": 6.0,
        "ingredients": [
            "tofu",
            "noodles",
            "peanut butter",
            "coconut milk",
            "bell pepper",
            "soy sauce",
        ],
    },
    {
        "name": "Hummus Chicken Pita",
        "description": "Chicken pita with hummus, cucumber, and tomato.",
        "cuisine": "Middle Eastern",
        "meal_type": "lunch",
        "calories": 550,
        "protein_g": 39,
        "carbs_g": 57,
        "fat_g": 19,
        "preparation_minutes": 18,
        "estimated_cost": 6.5,
        "ingredients": ["chicken breast", "pita", "hummus", "cucumber", "tomato"],
    },
]
